### ISSUE TITLE
Russian laguage generation

### ISSUE THREAD

**Issue by dagand1** [spiglerg/RNN_Text_Generation_Tensorflow#6]
Hi. Can I use it to generate text including russian words/language? Will it work correctly?

And can u explain me a lil' bit more about how to start generate text?

Cuz' when i choose new textfile to train and started with a command 'python rnn_tf.py' - I have been taking some OpKernels and warnigs + after that waiting for a long time (something like 2-3 hours). There was 800 batches and they didn't want to stop. I stoppped it by myself, cuz' losses was higher, then previos 700 batches.

After that i started with a command ' python rnn_ft.py  saved/model.ckpt "The " ' and programm returned me some errors.

Did i did everything right? Mb i should waight till train will be complete? Is it normal, that losses was growing up after 700 batches?

Sorry for my stupid questions and thanks :)

**Comment by spiglerg** [comment]
Yes is should work. This code learns a character-based language model, so it basically learns how likely are each character (regardless of the alphabet used) to appear after an observed sequence of other characters.

The code extracts the alphabet from the training text, so it will only learn to generate those characters:
```
data_ = ""
with open('data/shakespeare.txt', 'r') as f:
	data_ += f.read()
data_ = data_.lower()

## Convert to 1-hot coding
vocab = list(set(data_))
```

The current default training time (NUM_TRAINING_BATCHES) is 20.000. It is unlikely that any decent results will appear before many thousands iterations. In any case, you might adapt the code to generate a sample paragraph every 1000 iterations, to "see" the progress.

As for the model checkpoint I'm not sure, it's an old one so maybe it's just because of this. For now, you should try to train the model for a significant number of iterations (either on the dataset provided or on your own data), even though it may be very slow to do so. :/

**Comment by dagand1** [comment]
Thanks a lot :)
